<a href="https://colab.research.google.com/github/shivam-cse/CS-306-Machine-Learning-Work/blob/main/Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Part1_q1


In [ ]:
import numpy as np

array_10_zeros = np.zeros(10 , dtype='int')
array_10_ones = np.ones(10, dtype='int')
array_10_five = np.ones(10, dtype='int') * 5
arr=np.concatenate((array_10_zeros,array_10_ones,array_10_five))
print(arr)
#print("An array of 10 zeroes : ")
#print(array_10_zeros)
#print("An array of 10 ones : ")
#print(array_10_ones)
#print("An array of 10 fives : ")
#print(array_10_five)


[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]


Part1_q2


In [ ]:
import numpy as np

array = np.arange(10, 51, 2, dtype="int")

print(array)


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


Part1_q3

In [ ]:
import numpy as np
from numpy.random.mtrand import rand

# randNumber = np.random.uniform(0,1,30) #float between 0 to 1 size 3
randNumber = np.random.random() #it take only size and generate rand float value in between 0 to 1

print("rand Number", randNumber)

rand Numvber 0.10770930312397997


part1_q4

In [ ]:
import numpy as np

matrix = np.random.random(12).reshape(4,3)

print(matrix)

np.savetxt('data.txt',matrix, fmt="%f", header="\nThis is matrix data", footer="end..")

data_load = np.loadtxt("data.txt", dtype="double")
print("loaded data ..")
print(data_load)


[[0.07080124 0.61472358 0.84543519]
 [0.75071129 0.22085727 0.94561912]
 [0.29741058 0.1013267  0.24935258]
 [0.08001075 0.97843321 0.85591781]]
loaded data ..
[[0.070801 0.614724 0.845435]
 [0.750711 0.220857 0.945619]
 [0.297411 0.101327 0.249353]
 [0.080011 0.978433 0.855918]]


Part2_q1


In [ ]:
import numpy as np
import pandas as pd
import matplotlib.image as img


image_mat = img.imread("img1.jpg")
print("Shape of the image matrixe : ", image_mat.shape)


# now change our dimension
if image_mat.shape[2] == 3:
    # reshape from 3d to 2d matrixe
    new_image_mat = image_mat.reshape(image_mat.shape[0], -1)

else:
    new_image_mat = image_mat

# converting matrix to data frame using pandas
df_new_image_mat = pd.DataFrame(new_image_mat)
df_new_image_mat.to_csv('dataImg.csv', index=None, header=None)




Shape of the image matrixe :  (180, 280, 3)


Part2_q2

In [ ]:
import pandas as pd
import numpy as np
df =pd.read_csv('dataImg.csv')
new_df =pd.read_csv('dataImg.csv',nrows=len(df)-1,usecols=range(len(df.columns)-1))
print(new_df)

     1  2   7  1.1  2.1  7.1  1.2  ...  3.51  11.19  3.52  3.53  11.20  3.54  3.55
0    1  2   7    1    2    7    1  ...     3     11     3     3     11     3     3
1    1  2   7    1    2    7    1  ...     3     11     3     3     11     3     3
2    1  2   7    1    2    7    1  ...     3     11     3     3     11     3     3
3    1  2   7    1    2    7    1  ...     3     11     3     3     11     3     3
4    1  2   7    1    2    7    1  ...     3     11     3     3     11     3     3
..  .. ..  ..  ...  ...  ...  ...  ...   ...    ...   ...   ...    ...   ...   ...
173  5  5  13    5    5   13    5  ...     5     17     5     5     17     5     5
174  5  5  13    5    5   13    5  ...     5     17     5     5     17     5     5
175  2  8   8    2    8    8    2  ...     5     17     5     5     17     5     5
176  2  8   8    2    8    8    2  ...     5     17     5     5     17     5     5
177  2  8   8    2    8    8    2  ...     5     17     5     5     17     5     5

[17

Part2_q3

In [ ]:
import pandas as pd
from datetime import date

now = pd.to_datetime("now").date()
print("Today's date:")



Today's date:


Part3_q1

In [ ]:
#taken help from gfg

from datetime import date

def calculateAgeOfPerson(birthDate):
	days_in_year = 365.2425
	age_Of_person = int((date.today() - birthDate).days / days_in_year)
	return age_Of_person
		

DOB = input("Enter your Data of Birth(DD/MM/YYYY)")

#spliting data 
bday = DOB.split('/')
day = int(bday[0])
month = int(bday[1])
year = int(bday[2])

print(calculateAgeOfPerson(date(year,month,day)), "years old")



Enter your Data of Birth(DD/MM/YYYY)3/2/1997
24 years old


In [ ]:
from datetime import date

def calculateAge1OfPerson(birthDate):
      today = date.today()
      curr_date = int(today.day)
      curr_month = int(today.month)
      curr_year = int(today.year)

      user_date = int(birthDate.day)
      user_month = int(birthDate.month)
      user_year = int(birthDate.year)
      
      months = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

      if(user_date > curr_date):
        
      return user_date

DOB = input("Enter your Data of Birth(DD/MM/YYYY)")

#spliting data 
bday = DOB.split('/')
day = int(bday[0])
month = int(bday[1])
year = int(bday[2])

print(calculateAge1OfPerson(date(year,month,day)), "years old")

Enter your Data of Birth(DD/MM/YYYY)2/3/4
2 years old
